beta=500;%factoru de amplificare in curent
Ro= 0;%rezistenta de iesire
Ri=0;%rezistenta de intrare
gm=0;%trasconductanta
rbe=0;%rezistivitatea baza emitor
Av=0;%amplificare tensiune
Ai=0;%amplificare curent
RB1=5000;
RB2=5000;
VAl=15;%alimentarea
RC=1000;
RE=500;
VCE=0;
IC=0;
A=1;
f=10;
N=10;
tip=1;

Fig=figure('Name','Proiect',...
    'Units','normalized',...
    'Position',[0.07 0.2 0.6 0.4],...
    'NumberTitle','off','color',[0.75,0.75,0.75]);  

f0=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'ForegroundColor','black',...
    'Position',[0.15 0.7 0.3 0.2],...
    'String','documentatie',...
    'Callback','open(''Presentation.pdf'')');

f1=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'ForegroundColor','black',...
    'Position',[0.15 0.5 0.3 0.2],...
    'String','Tranzistoru BC',...
    'Callback','project_2(beta,Ro,Ri,gm,rbe,Av,Ai,RB1,RB2,VAl,RC,RE,IC,VCE,A,f,N,tip)');


